### ISSUE TITLE
1191的solution无法通过test case 43/44

### ISSUE THREAD

**Issue by mirinta** [wisdompeak/LeetCode#101]
位置：maxSubArrSum函数的第37行。

原因：代码里对max_ending_here先做取模运算，再与max_so_far比较，但比较运算应放在取模运算之前。比如 1 % 4 > 4 % 4，但实际上1 < 4。

改正：删掉第34行，并将第23行的`maxSubArrSum(arr)`改成`maxSubArrSum(arr)%M`。

**Comment by yangizone** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wisdompeak** [comment]
谢谢提醒，已改正。
