### ISSUE TITLE
2366.Minimum-Replacements-to-Sort-the-Array solution 2 proof

### ISSUE THREAD

**Issue by Zackhardtoname** [wisdompeak/LeetCode#102]
第二种解法，怎么证明⌈y/k⌉不会超过x？

可以表达成
If we know a > b, is this always true?
`ceil(a / (floor(a, b) + 1) <= b`

**Comment by yangizone** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wisdompeak** [comment]
let a = k*b + f*b where k is an integer and f is a real number in (0,1)

LFET = ceil (a / (k + 1))  = ceil( (k+f)/(k+1) * b ) <= ceil(b) = b

**Comment by Zackhardtoname** [comment]
啊 好棒 感谢！
