### ISSUE TITLE
题目分类表里面的难度评价是否存在疏忽写错之处，如官标简单的168题此评价系统为困难

### ISSUE THREAD

**Issue by CarlCzerny837** [wisdompeak/LeetCode#20]
168题属于进制转换，只是因为没有0会产生一些额外细节，官标为简单，但主页把这个题目评为H，是否原意打E或M出现疏忽？

另外85题需要用到84题的代码，还要先做预处理成84题的情形才能用单调栈来解，难度不应该比84低
449题完全可以直接复制297题的代码，难度不应该比297更高（虽然更好的做法是用前序来序列化，然后用105题的方法还原）

**Comment by wisdompeak** [comment]
这里的难度评价只是我的主观评价，综合了各方面考虑的因素。

168是很早的时候做的，一直没有复盘（所有没有链接）。当时在各种细节上WA了很多次，所以我觉得是H。当然，现在来看可能不至于，但我觉得还是有点难度。

85的核心就是84，所以84坐会了，85的难度就下去了。

449虽然可以赋值297的做法，但显然那不是最优解。所以难度比297高。

这些标注就当图一乐。

**Comment by CarlCzerny837** [comment]
> 这里的难度评价只是我的主观评价，综合了各方面考虑的因素。
> 
> 168是很早的时候做的，一直没有复盘（所有没有链接）。当时在各种细节上WA了很多次，所以我觉得是H。当然，现在来看可能不至于，但我觉得还是有点难度。
> 
> 85的核心就是84，所以84坐会了，85的难度就下去了。
> 
> 449虽然可以赋值297的做法，但显然那不是最优解。所以难度比297高。
> 
> 这些标注就当图一乐。

感谢大佬的回复~

**Comment by zhfkt** [comment]
实际上168是挺难的，在中文主站上有大量的人卡住，实际上至少是一道medium。每次循环-1的巧妙做法，没做过不一定可以想到。想到了也不一定能够证明。

![image](https://user-images.githubusercontent.com/4969804/193411993-b9a4f62a-e106-4b70-a849-db535023de8d.png)
![image](https://user-images.githubusercontent.com/4969804/193412003-d37fef79-42ef-47bf-bc3f-37d019254b24.png)
