### ISSUE TITLE
2096，依照老师的c++代码，改成java后提交不通过。请看看哪里出了问题？

### ISSUE THREAD

**Issue by tengshengwei** [wisdompeak/LeetCode#23]
public String getDirections(TreeNode root, int startValue, int destValue) {
          List<Integer> nums1 = new ArrayList<>();
          List<Integer> nums2 = new ArrayList<>();
          List<Character> dirs1 = new ArrayList<>();
          List<Character> dirs2 = new ArrayList<>();
          dfs(root, nums1, dirs1, startValue);
          dfs(root, nums2, dirs2, destValue);
  
          int k = 0;
          while (k<nums1.size() && k<nums2.size() && nums1.get(k)==nums2.get(k))
              k++;
          for (int i=k; i<dirs1.size(); i++) dirs1.set(i,'U');
  
          StringBuilder str = new StringBuilder();
          for (Character character : dirs1.subList(k,dirs1.size())) {
              str.append(character);
          }
          for (Character character : dirs2.subList(k,dirs2.size())) {
              str.append(character);
          }
          return str.toString();
      }
  
      private boolean dfs(TreeNode node, List<Integer> nums, List<Character> dirs, int target) {
          if (node==null) return false;
          if (node.val == target) return true;
          if (node.left!=null)
          {
              nums.add(node.left.val);
              dirs.add('L');
              if (dfs(node.left, nums, dirs, target))
                  return true;
              nums.remove(nums.size()-1);
              dirs.remove(dirs.size()-1);
          }
          if (node.right!=null)
          {
              nums.add(node.right.val);
              dirs.add('R');
              if (dfs(node.right, nums, dirs, target))
                  return true;
              nums.remove(nums.size()-1);
              dirs.remove(dirs.size()-1);
          }
          return false;
      }

**Comment by tengshengwei** [comment]
找到问题了

**Comment by wisdompeak** [comment]
我简单的debug发现这一行
```
      while (k<nums1.size() && k<nums2.size() && nums1.get(k)==nums2.get(k))
          k++;
```
里尽管nums1[0]==nums2[0]，但是k也并没有增加。我不会Java。我猜是你用的List<Integer>这个数据结构有问题。

**Comment by longwei** [comment]
Java非primity type的比较要用equals()

**Comment by Bill0412** [comment]
不然比较的是address吗

**Comment by Bill0412** [comment]
> Java非primitive type的比较要用equals()

不然比较的是address吗（不会Java，猜测

**Comment by tengshengwei** [comment]
@longwei 感谢，改成while (k<nums1.size() && k<nums2.size() && nums1.get(k).equals(nums2.get(k))) ，就通过了
