### ISSUE TITLE
1982.Find-Array-Given-Subset-Sums.cpp is TLE

### ISSUE THREAD

**Issue by JIACHENG135** [wisdompeak/LeetCode#27]
Hello wisdompeak,

Thanks for your sharing! I have learned a lot from your codes. I tried to follow your method for leetcode 1982 but find your solution is now graded as TLE. Which step do you think can be improved in order to get accepted? Once i figured it out, i will close this ticket. Thanks again. 
![image](https://user-images.githubusercontent.com/31320373/150884226-add45f9f-059e-4c6c-96ef-c10c72ac7779.png)

**Comment by wisdompeak** [comment]
我新增了改进的写法，见 https://github.com/wisdompeak/LeetCode/blob/master/Greedy/1982.Find-Array-Given-Subset-Sums/1982.Find-Array-Given-Subset-Sums_v2.cpp
基本原理和2007和2122差不多，就是用双支针而不是multiset，把混合了{nums[i]}与{nums[i]+x}的数组分离出{nums[i]}来。

**Comment by wisdompeak** [comment]
请参见更新后的代码。
