### ISSUE TITLE
956题18行有笔误

### ISSUE THREAD

**Issue by Anudorannador** [wisdompeak/LeetCode#31]
https://github.com/wisdompeak/LeetCode/blob/732c60732b926004a19bf614386b8c649d7297fd/Dynamic_Programming/956.Tallest-Billboard/956.Tallest-Billboard.cpp#L18

这一行笔误了，应该是 
```
if (diff+x<B) dp[j+x] = max(dp[j+x],dp_temp[j]+x);
                                               ↑
```

因为第10行是 `for (auto x: rods)`

**Comment by wisdompeak** [comment]
谢谢提醒，已改正。
