### ISSUE TITLE
函数参数类型不一致

### ISSUE THREAD

**Issue by Anudorannador** [wisdompeak/LeetCode#32]
https://github.com/wisdompeak/LeetCode/blob/69b113a06c16d9fca9577d10d8d17784290ef9c7/Greedy/452.Minimum-Number-of-Arrows-to-Burst-Balloons/452.Minimum-Number-of-Arrows-to-Burst-Balloons.cpp#L7

原题的函数定义是 `findMinArrowShots(vector<vector<int>>& points)`，类型是 `vector<vector<int>>` ，不是 `vector<pair<int, int>>`。所以代码里的 `first` 和 `second` 对应也需要修改。

我试了下，修改函数会报编译错误。

```
Line 30: Char 46: error: non-const lvalue reference to type 'vector<pair<int, int>>' cannot bind to a value of unrelated type 'vector<vector<int>>'
      int ret = Solution().findMinArrowShots(param_1); return ret;
                                             ^~~~~~~
Line 7: Char 51: note: passing argument to parameter 'points' here
    int findMinArrowShots(vector<pair<int, int>>& points)
                                                  ^
1 error generated.
```

PS：是不是关神做的时候题目是 `pair` 后来改成 `vector` : )

**Comment by wisdompeak** [comment]
是的，在远古的时候很多题目参数都是用的pair。
