### ISSUE TITLE
LeetCode 1522库里的代码跑出来是WA，要修改一下代码哦~另外谢谢feng哥的解答！

### ISSUE THREAD

**Issue by Algo-Goer** [wisdompeak/LeetCode#36]
[1,null,2,3,4,5,null,null,6,7,null,8,null,9,10,null,null,11,null,12,null,13,null,null,14] 代码跑出来是WA，需要把代码中的depths.back()改成depths[0]就可以AC啦~

**Comment by yangizone** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by YaoyaoChang** [comment]
您好，您的邮件我已经收到，我一定会尽快回复的！谢谢！【此为自动回复邮件】Hello, I've received your email. I will reply to you as soon as possible! Thank you! 【This is an automatic reply email】

**Comment by wisdompeak** [comment]
谢谢指出，已修正。
