### ISSUE TITLE
The Template of SegmentTree may be wrong?

### ISSUE THREAD

**Issue by ZjuYTW** [wisdompeak/LeetCode#55]
https://github.com/wisdompeak/LeetCode/blob/master/Template/SegmentTree/range_sum.cpp#L33
In the `PushDown` method of RangeSum temlpate, the code just simply copy the parent's info to childrens',  which is wrong.

I test it by the following code
```c++
int main(){
    SegTreeNode* root = new SegTreeNode(0, 10, 0);
  
    root->updateRange(5, 10, 20);

    assert(root->queryRange(6,6) == 20); // where the template gives us 40
}
```

We could fix this by introducing `lazy_val` as the member variable.

**Comment by wisdompeak** [comment]
谢谢提醒。简单修正了一下，欢迎测试。
