### ISSUE TITLE
Leetcode 87 solution can not pass currently

### ISSUE THREAD

**Issue by zhfkt** [wisdompeak/LeetCode#61]
https://github.com/wisdompeak/LeetCode/blob/718bd0d15e98c5fe288420d05d04becde2829c68/Recursion/087.Scramble-String/087.Scramble-String.cpp#L1

It failed on the following Test Case (286 / 288 passed):

```
"eebaacbcbcadaaedceaaacadccd"
"eadcaacabaddaceacbceaabeccd"
```

I checked we may use _3-dim dp_ or _memory recursion_  instead on this solution

**Comment by wisdompeak** [comment]
谢谢提醒，已经更新代码。
