### ISSUE TITLE
递归更简洁

### ISSUE THREAD

**Issue by daixiongming** [wisdompeak/LeetCode#63]
222. Count Complete Tree Nodes

class Solution {
public:
    int countNodes(TreeNode* root) {
        if(!root){
            return 0;
        }

        int countL=countNodes(root->left);
        int countR=countNodes(root->right);
        return countL+countR+1;

    }
};

**Comment by wisdompeak** [comment]
你的这个写法没有用到complete tree的性质，时间复杂度不是题目所期望的。

**Comment by daixiongming** [comment]
I am agree

wisdompeak ***@***.***>于2022年9月18日 周日14:21写道：
