### ISSUE TITLE
Leetcode 156 直接递归，代码更简洁直观。

### ISSUE THREAD

**Issue by daixiongming** [wisdompeak/LeetCode#64]
class Solution156 {
public:
    TreeNode* upsideDownBinaryTree(TreeNode* root) {
        if (!root) return nullptr;
        if (!root->left && !root->right) return root;
        TreeNode* trueRoot = upsideDownBinaryTree(root->left);
        //update the new branches
        root->left->left = root->right;
        root->left->right = root;
        root->left = nullptr;
        root->right = nullptr;
        return trueRoot;

    }

};

**Comment by wisdompeak** [comment]
Fixed. Thanks.
