### ISSUE TITLE
1798. belongs to Greedy, not Two Pointers?

### ISSUE THREAD

**Issue by AnCheTeng** [wisdompeak/LeetCode#74]
Hi Hui-Feng,

I'm studying with your amazing guide and I found that [1798. Maximum-Number-of-Consecutive-Values-You-Can-Make](https://github.com/wisdompeak/LeetCode/blob/master/Greedy/1798.Maximum-Number-of-Consecutive-Values-You-Can-Make) in Readme.md is categorized in Two Pointers, but it's solution is Greedy.

**Comment by wisdompeak** [comment]
Fixed. Thank you for letting me know.
