### ISSUE TITLE
260- Single Numbers III

### ISSUE THREAD

**Issue by xymabinogi** [wisdompeak/LeetCode#75]
https://github.com/wisdompeak/LeetCode/blob/master/Bit_Manipulation/260.Single-Number-III/260.Single-Number-III.cpp

s-1 在s取INT_MIN的时候会RE，这题可能直接用builtin_ctz之类的比较安全(题前的md可能也需要稍微改一下)。

**Comment by wisdompeak** [comment]
Good point。不过考虑到INT_MIN在计算机中的表达方式，应该能知道s不可能会是INT_MIN。
