### ISSUE TITLE
关于heap分类的疑惑

### ISSUE THREAD

**Issue by XuRunheng** [wisdompeak/LeetCode#78]
大佬，在下不是很明白为什么set的题目放到heap分类  c++的set是用红黑树实现的 priorityqueue才是用heap实现的

**Comment by yangizone** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wisdompeak** [comment]
你的说法是正确的。这是历史遗留问题。最早我把pq和set的题都放在一起，归类为一系列涉及到自动排序的数据结构的题目。后来我把pq另外分出来了，heap这个词对set而言反而就不合适了。我还没想好怎么重命名这么多文件，就先这么凑活儿叫吧。
