### ISSUE TITLE
关于二分查找代码的疑问

### ISSUE THREAD

**Issue by riverbuilding** [wisdompeak/LeetCode#81]
你好，请问如下问题，在二分查找的代码中，计算mid有两种写法：
int mid = low+(high-low)/2;
int mid = right-(right-left)/2;

这两种写法分别对应什么情况？能稍微解释一下吗？

**Comment by wisdompeak** [comment]
这两种写法都是在[low,high]里找一个中间点。如果这个区间的长度是偶数，那么前者会靠中间偏左一点，后者会靠中间偏右一点。选择哪一种，取决于你后面更新low和high时的写法。选择的目的是确保下个回合二分搜索的区间不会出现死循环。比如说当前的[low,high]=[0,1]，你任意取一种mid的写法：然后你发现按照你后面的low和high的更新写法，下一个回合的区间仍然是[0,1]，那么意味着你的mid必须选择另外一种写法（这样可以收敛到[0,0]或者[1,1]）。

**Comment by yangizone** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by riverbuilding** [comment]
> 区间的长度是偶数

知道了，多谢多谢

**Comment by wisdompeak** [comment]
solved

**Comment by Bill0412** [comment]
看来你没有仔细看过去的一些视频，群主基本每期相关视频都会讲。

**Comment by BeeHuang** [comment]
**### 首先非常感謝版主一直分享視頻．**

我有發摟版主的視頻，也有上面的解答，但始終 一直心裡有疑惑，以下是我解開自己的疑惑的回覆，供大家參考

以下分 3 段回答
1. 問題描述
2. Example
3. How
--------------


**### 1. 問題描述**
---------
理解版主說的，[0,1]時，用不同的方式 會有不同的mid值.
但看到題目時，我就不是不知道要怎麼使用. 是要用 mid = 0 (left + (right-left)/2)還是 mid = 1 (right - (right-left)/2).


**### 2. Example - 題目分兩分種**
---------
2.1 求最大
ex: longest (最長 = 最大)
https://github.com/wisdompeak/LeetCode/blob/2a675d7d62835bb5c62faf383b4a522b7be2dbb1/String/1923.Longest-Common-Subpath/1923.Longest-Common-Subpath.cpp#L10

2.2 求最小
ex: earliest (最早 = 最小) https://github.com/wisdompeak/LeetCode/blob/2a675d7d62835bb5c62faf383b4a522b7be2dbb1/Greedy/2136.Earliest-Possible-Day-of-Full-Bloom/2136.Earliest-Possible-Day-of-Full-Bloom_v1.cpp#L16



**### 3. How**
---------
這兩種 有什麼差別?

3.1 最大 --> 就是要BS 要往右邊走 --> 因排好序的，最大值在 array在右邊

使用 搭配如下
mid = right - (right-left)/2
left = mid 
right = mid - 1 

3.2 最小 --> BS 往左邊走 -->   因排好序的，最大小在 array在左邊

使用 搭配如下
mid = left + (right-left)/2
right = mid
left = mid +1

**Comment by wisdompeak** [comment]
我的本意是，不用关心mid的写法。等你把left=...和right=...写完之后，为了保证不出现死循环，mid=...的写法自然就唯一确定下来了。
