### ISSUE TITLE
699 解法1 更新 right+1 边界时，未考虑是否会破坏原 right  +1

### ISSUE THREAD

**Issue by zhi-zhi-zhi** [wisdompeak/LeetCode#88]
# 测试数据
测试用例：[[1,1],[2,5],[1,1],[2,5]]
预计输出：[1, 5, 5, 10]
实际输出：[1, 5, 5, 6]

## 文字描述
map[2] 原为 5，第二个 [1,1] 更新时，会将 map[2] 更新为 1 （原 map[1]）
导致 第二个 [2,5] 将 map[2] 更新为 6 = (2 + 5)，实际应是 10 = (5  +5)

## map 更新过程：
0 0
1 1
2 0
2147483647 0

0 0
1 1
2 5
7 0
2147483647 0

0 0
1 2
2 1
7 0
2147483647 0

0 0
1 2
2 6
7 1
2147483647 0

**Comment by wisdompeak** [comment]
Thanks for fixing it.
