### ISSUE TITLE
805题第二种做法

### ISSUE THREAD

**Issue by yuanlu0210** [wisdompeak/LeetCode#9]
805题第二种做法 805.Split-Array-With-Same-Average_DP2.cpp 好像没有考虑到全零并且长度大于1的test case，比如[0, 0, 0, 0, 0]，在第20行`if (sum*n%total!=0) continue;`处会出现division by zero的错误。

**Comment by wisdompeak** [comment]
Updated.  Add pre-check:
```cpp
if (total==0) return true;
```
