### ISSUE TITLE
双指针解法疑问

### ISSUE THREAD

**Issue by bobosolomon** [wisdompeak/LeetCode#92]
在双指针解法中，应该考虑的是 `A[i] == 0` 和 `A[i] == 1` 的情况，而不是考虑 `A[i+1]`的取值？

**Comment by MeteorVE** [comment]
哥你好歹給個題號吧

**Comment by bobosolomon** [comment]
不好意思，第一次提issue， 题号是[1004.Max-Consecutive-Ones-III](https://github.com/wisdompeak/LeetCode/tree/master/Two_Pointers/1004.Max-Consecutive-Ones-III)

**Comment by wisdompeak** [comment]
原来的文字逻辑没表述清楚，已更新。
