### ISSUE TITLE
532 KDiffPairInAnArray

### ISSUE THREAD

**Issue by ReveStar** [wisdompeak/LeetCode#93]
应该不需要重新定位j的位置？排序后i右移后值变大，与j对应值的差必然是小于k的。

**Comment by yangizone** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wisdompeak** [comment]
需要保证j必须在i的后面。
