### ISSUE TITLE
Add redis store library for basic operations

### ISSUE THREAD

**Issue by b06902044** [wisdompeak/LeetCode#97]

**Comment by YaoyaoChang** [comment]
您好，您的邮件我已经收到，我一定会尽快回复的！谢谢！【此为自动回复邮件】Hello, I've received your email. I will reply to you as soon as possible! Thank you! 【This is an automatic reply email】

**Comment by yangizone** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
